version: '3.8'

services:
  antminer-exporter:
    build: .
    container_name: antminer-exporter
    ports:
      - "9100:9100"
    volumes:
      - ./config.py:/app/config.py
      - ./logs:/app/logs
    restart: unless-stopped
