version: '3.8'

services:
  exporter:
    container_name: antminer-exporter
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9222:9222"
    volumes:
      - miners.yml:./miners.yml
    restart: unless-stopped
#    depends_on:
#      - victoria

  # Example service for VictoriaMetrics (requires separate setup)
  victoria:
    image: grafana/victoria-metrics:latest # Use actual recommended image
    container_name: victoria
    ports:
      - "8428:8428"
    restart: unless-stopped
